execute_process(COMMAND "${RUNNER}" "${MODE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
if(MODE STREQUAL "leak")
    if(NOT status EQUAL 2 OR NOT err MATCHES "LeakSanitizer: detected memory leaks" OR
       NOT err MATCHES "RF fatal: explicit LSan check=1")
        message(FATAL_ERROR "Deliberate leak was not detected (${status}): ${out}${err}")
    endif()
elseif(MODE STREQUAL "reentry")
    if(NOT status EQUAL 1 OR NOT err MATCHES "re-entry during teardown")
        message(FATAL_ERROR "Reentry guard failed (${status}): ${out}${err}")
    endif()
else()
    if(NOT status EQUAL 7)
        message(FATAL_ERROR "Positive exit status was lost (${status}): ${out}${err}")
    endif()
    if(SANITIZED AND NOT err MATCHES "RF fatal: explicit LSan check=0")
        message(FATAL_ERROR "Explicit leak check missing: ${out}${err}")
    endif()
endif()
