file(MAKE_DIRECTORY "${FIXTURE_DIR}/bitmaps/inventory")
file(COPY "${NEUTRAL_DIR}/RealityFactory.ini" "${NEUTRAL_DIR}/install"
    "${NEUTRAL_DIR}/bitmaps" DESTINATION "${FIXTURE_DIR}")
file(COPY "${NEUTRAL_DIR}/bitmaps/menu/neutral.bmp" "${NEUTRAL_DIR}/bitmaps/menu/alpha.bmp"
    DESTINATION "${FIXTURE_DIR}/bitmaps/inventory")
set(config "[Inventory]\nbackground=neutral.bmp\nhighlight=neutral.bmp\nhighlightalpha=alpha.bmp\n")
if(PROFILE STREQUAL "valid")
    string(APPEND config "arrowr=neutral.bmp\narrowl=neutral.bmp\narrowrhighlight=neutral.bmp\narrowlhighlight=neutral.bmp\n")
elseif(PROFILE STREQUAL "partial")
    string(APPEND config "arrowr=neutral.bmp\n")
elseif(NOT PROFILE STREQUAL "absent")
    if(PROFILE STREQUAL "arrowralpha")
        string(APPEND config "arrowr=neutral.bmp\n")
    elseif(PROFILE STREQUAL "arrowlalpha")
        string(APPEND config "arrowl=neutral.bmp\n")
    endif()
    string(APPEND config "${PROFILE}=missing.bmp\n")
endif()
file(WRITE "${FIXTURE_DIR}/install/Inventory.ini" "${config}")
execute_process(COMMAND "${XVFB}" -a -s "-screen 0 640x480x24"
    "${RUNNER}" --boot-stage=2 "--config-dir=${FIXTURE_DIR}"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 25)
set(log "${out}\n${err}")
file(WRITE "${FIXTURE_DIR}/inventory-schema.log" "${log}")
if(log MATCHES "ERROR: (AddressSanitizer|LeakSanitizer)|runtime error:")
    message(FATAL_ERROR "Inventory schema sanitizer failure (${status}): ${log}")
endif()
if(PROFILE STREQUAL "absent" OR PROFILE STREQUAL "valid" OR PROFILE STREQUAL "partial")
    if(NOT status EQUAL 0 OR NOT log MATCHES "RF inventory fixture: constructor returned" OR
       NOT log MATCHES "RF inventory fixture: four paginated draw branches returned" OR
       NOT log MATCHES "RF inventory fixture: destructor returned" OR NOT log MATCHES "RF native exit: 0")
        message(FATAL_ERROR "Inventory schema construction failed (${status}): ${log}")
    endif()
    if(PROFILE STREQUAL "absent")
        string(REGEX MATCHALL "inventory: arrow bitmaps absent \\(pre-0.68 config\\)" notices "${log}")
        list(LENGTH notices count)
        if(NOT count EQUAL 1)
            message(FATAL_ERROR "Expected exactly one pre-0.68 diagnostic: ${log}")
        endif()
    elseif(log MATCHES "inventory: arrow bitmaps absent")
        message(FATAL_ERROR "Present arrows incorrectly reported absent: ${log}")
    endif()
else()
    if(NOT status EQUAL 1 OR NOT log MATCHES "Missing Data in Inventory" OR
       NOT log MATCHES "RF fatal: stage=2 code=-333 exit=1" OR
       log MATCHES "RF inventory fixture: constructor returned")
        message(FATAL_ERROR "Invalid explicit bitmap was not rejected (${status}): ${log}")
    endif()
    if(SANITIZED AND NOT log MATCHES "RF fatal: explicit LSan check=0")
        message(FATAL_ERROR "Fatal inventory path did not reach the existing LSan check: ${log}")
    endif()
endif()
