#!/usr/bin/env python3
"""Derive the native userdata-size table from the active upstream project graph.

Default output is stdout; --check validates the committed generated header.
No authored data or platform-dependent numeric sizes are embedded.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "adapters/entity_sizes.generated.h"
TOKENS = re.compile(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'', re.S)
CALL = re.compile(r'\bgeEntity_GetUserData\s*\(')
CAST = re.compile(r'\(\s*([A-Za-z_]\w*)\s*\*\s*\)\s*geEntity_GetUserData\s*\(')


def code_only(text):
    return TOKENS.sub(lambda m: " " * len(m[0]), text)


def generate():
    project = (ROOT / "upstream/RealityFactory.vcproj").read_text()
    units = re.findall(r'RelativePath="([^\"]+\.(?:c|cpp))"', project)
    if len(units) != 157 or len(set(units)) != 157:
        raise ValueError("active runtime graph changed; review the generator scope")
    legacy_units = ["CNPC.cpp", "CNPCPathPoint.cpp", "Track.cpp",
                    "LegacyNPCUtilities.cpp"]
    sources = {}
    names = set()
    count = 0
    unit_paths = []
    for unit in units:
        unit = unit.replace("\\", "/")
        if unit == "drawbbox.c":
            unit = "Drawbbox.c"
        unit_paths.append((unit, ROOT / "upstream" / unit))
    unit_paths.extend((f"upstream-0.68a/{unit}", ROOT / "upstream-0.68a" / unit)
                      for unit in legacy_units)
    for unit, path in unit_paths:
        text = code_only(path.read_text(errors="replace"))
        sources[unit] = text
        matches = list(CAST.finditer(text))
        calls = list(CALL.finditer(text))
        recognized = {m.end() for m in matches}
        all_calls = {m.end() for m in calls}
        if recognized != all_calls:
            # The recovered path-point constructor stores one userdata result
            # in void* before its immediately following typed assignment.
            if unit != "upstream-0.68a/CNPCPathPoint.cpp" or len(all_calls - recognized) != 1:
                raise ValueError(f"unrecognized userdata cast in {unit}")
            names.add("NPCPathPoint")
        names.update(m[1] for m in matches)
        count += len(calls)
    shared = code_only((ROOT / "upstream/GameEntityDataTypes.h").read_text(errors="replace"))
    shared += code_only((ROOT / "upstream-0.68a/LegacyNPCEntityDataTypes.h").read_text(errors="replace"))
    local = {}
    for name in sorted(names):
        if re.search(r'}\s*' + re.escape(name) + r'\s*;', shared):
            continue
        pattern = re.compile(r'typedef\s+struct\s+\w+\s*\{[^{}]*\}\s*' + re.escape(name) + r'\s*;', re.S)
        definitions = [(unit, m[0]) for unit, text in sources.items() for m in pattern.finditer(text)]
        if len(definitions) != 1:
            raise ValueError(f"cannot derive unique local declaration for {name}")
        local[name] = definitions[0]
    lines = ["/* Generated by tools/gen_entity_sizes.py; do not edit.",
             f" * Active units: {len(unit_paths)}; userdata casts: {count}; distinct types: {len(names)}.",
             " * Numeric sizes are computed by this build's C++ compiler. */",
             "namespace RFSchemaLocal {"]
    for name, (unit, declaration) in sorted(local.items()):
        lines += [f"// File-local declaration derived from {unit}.",
                  re.sub(r'\s+', ' ', declaration)]
    lines += ["}", "static const RFEntitySize rf_entity_sizes[] = {"]
    for name in sorted(names):
        typename = "RFSchemaLocal::" + name if name in local else name
        lines.append(f'    {{"{name}", sizeof({typename})}},')
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        expected = generate()
        if args.check:
            if not OUTPUT.exists() or OUTPUT.read_text() != expected:
                raise ValueError("entity size table is stale; regenerate and review the diff")
            print("entity size table: PASS")
        else:
            sys.stdout.write(expected)
    except (OSError, ValueError) as error:
        print(f"entity size table: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
