#!/usr/bin/env python3
"""Generate application field layouts; --check rejects stale committed output."""
import argparse
import re
import sys
from gen_entity_sizes import ROOT, code_only, generate as sizes

OUTPUT = ROOT / "adapters/entity_schema.generated.h"
DEFAULT = re.compile(
    r'#\s*pragma\s+GE_DefaultValue\s*\(\s*(\w+)\s*,\s*("(?:\\.|[^"\\])*")\s*\)')


def source_struct(text, name):
    match = re.search(r'typedef\s+struct\s+\w+\s*\{([^{}]*)\}\s*' +
                      re.escape(name) + r'\s*;', text, re.S)
    return match[1] if match else None


def generate():
    size_text = sizes()
    names = re.findall(r'\{"(\w+)", sizeof\(([^)]+)\)\}', size_text)
    if len(names) != 67:
        raise ValueError("review changed 67-class scope")
    sources = [
        (ROOT / "upstream/GameEntityDataTypes.h").read_text(errors="replace"),
        (ROOT / "upstream-0.68a/LegacyNPCEntityDataTypes.h").read_text(errors="replace"),
    ]
    lines = ["/* Generated by tools/gen_entity_schema.py; do not edit.",
             " * Field order comes from source; compiler verifies every native offset. */"]
    total = 0
    defaults_total = 0
    stale_defaults_total = 0
    entries = []
    for name, typename in names:
        raw = next((body for source in sources
                    for body in [source_struct(source, name)] if body is not None), None)
        if raw is None:
            raw = source_struct(size_text, name)
        if raw is None:
            raise ValueError(f"missing declaration: {name}")
        defaults = {}
        for field, value in DEFAULT.findall(raw):
            if field in defaults:
                raise ValueError(f"duplicate default in {name}.{field}")
            defaults[field] = value
        body = re.sub(r'^\s*#.*$', '', code_only(raw), flags=re.M)
        fields = []
        for declaration in body.split(';'):
            declaration = declaration.strip()
            if not declaration:
                continue
            m = re.fullmatch(r'(\w+)\s+(.+)', declaration, re.S)
            if not m:
                raise ValueError(f"unsupported declaration in {name}: {declaration}")
            base, rest = m.groups()
            for member in rest.split(','):
                m = re.fullmatch(r'\s*(\**)\s*(\w+)\s*', member)
                if not m:
                    raise ValueError(f"unsupported member in {name}: {member}")
                pointer, field = m.groups()
                if pointer:
                    mapped = 'string' if base == 'char' and pointer == '*' else 'model' if base == 'geWorld_Model' and pointer == '*' else 'ptr'
                    native = 'void *'
                else:
                    mapped = {'geVec3d': 'point', 'GE_RGBA': 'color', 'geFloat': 'geFloat',
                              'geBoolean': 'int', 'int': 'int'}.get(base)
                    native = 'int32' if mapped == 'int' else base
                if not mapped:
                    raise ValueError(f"unmapped type {base} in {name}.{field}")
                fields.append((field, mapped, native, defaults.get(field, 'NULL')))
        unknown = set(defaults) - {field for field, _, _, _ in fields}
        # Inherited headers retain a few pragmas for fields removed from the
        # surrounding struct. They are not declarations and cannot be emitted.
        stale_defaults_total += len(unknown)
        lines.append(f'static const geEntity_FieldDecl rf_fields_{name}[] = {{')
        lines.extend(f'    {{"{f}", "{t}", {default}}},'
                     for f, t, _, default in fields)
        lines.append('};')
        previous = '0'
        for i, (field, _, native, _) in enumerate(fields):
            # __alignof__ is supported by the GCC/Clang C++98 targets.
            offset = f'(({previous} + __alignof__({native}) - 1) & ~(__alignof__({native}) - 1))'
            lines.append(f'typedef char rf_layout_{name}_{i}[(offsetof({typename}, {field}) == {offset} && sizeof((({typename} *)0)->{field}) == sizeof({native})) ? 1 : -1];')
            previous = f'(offsetof({typename}, {field}) + sizeof((({typename} *)0)->{field}))'
        entries.append(f'    {{"{name}", rf_fields_{name}, {len(fields)}}},')
        total += len(fields)
        defaults_total += len(defaults)
    lines += ['static const RFEntitySchema rf_entity_schemas[] = {', *entries, '};',
              f'/* {len(names)} classes, {total} fields, {defaults_total - stale_defaults_total} declaration defaults; '
              f'{stale_defaults_total} stale pragmas ignored. */', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        text = generate()
        if args.check:
            if not OUTPUT.exists() or OUTPUT.read_text() != text:
                raise ValueError('entity schema table stale; regenerate and review')
            print('entity schema table: PASS')
        else:
            sys.stdout.write(text)
    except (OSError, ValueError) as error:
        print(f'entity schema: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
